
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 17 01:19:12 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 40;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int NAMESPACE = 17;
  public static final int IMPL = 44;
  public static final int LPAREN = 38;
  public static final int SEMI = 34;
  public static final int CONTINUE = 14;
  public static final int FOR = 15;
  public static final int MINUS = 19;
  public static final int RPAREN = 39;
  public static final int STATIC = 16;
  public static final int DEFINE = 31;
  public static final int AND = 29;
  public static final int OR = 30;
  public static final int BOOL = 47;
  public static final int COMMA = 36;
  public static final int CLASS = 4;
  public static final int PERC = 22;
  public static final int INC = 32;
  public static final int DIV = 21;
  public static final int PLUS = 18;
  public static final int IF = 7;
  public static final int DOT = 37;
  public static final int LEFT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int RBRACKET = 41;
  public static final int EQUAL = 23;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 20;
  public static final int NUMBER = 48;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int COLON = 35;
  public static final int LBRACE = 42;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int GOTO = 45;
  public static final int RBRACE = 43;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int RIGHTEQ = 26;
  public static final int DEC = 33;
  public static final int RIGHT = 25;
  public static final int PRINT = 9;
  public static final int UNEQUAL = 24;
  public static final int LEFTEQ = 28;
}

